version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    container_name: insulA_container
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: insula
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: insula
  
  # Servicio para pgAdmin
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin